### ISSUE TITLE
enhancement: logX should not be a string interpolator

### ISSUE THREAD

**Issue by pfn** [macroid/macroid#35]
it removes room for one to use other string interpolators, e.g. for formatting (f)

also, logX doesn't do anything special other than insert the variables. no reason to use string interp. and it looks ugly

`logV"foo"()` ? yuck  :(

`logV(f"$interp%02d")` that's pretty reasonable (all other implicits for logtag, etc. are ok)

**Comment by stanch** [comment]
I’ve just noticed that the commit referenced here went into `M4`. I’m not very happy about the object creation overhead. Regardless, do you guys think we actually need any logging functionality in *Macroid*? Probably *slf4j-android* + *scala-logging* give the same effect with more flexibility...
