### ISSUE TITLE
Going through library sources within IDE

### ISSUE THREAD

**Issue by dant3** [macroid/macroid#39]
Trying to go through library sources to see how it works in Idea gives me this sad screen:
![image](https://cloud.githubusercontent.com/assets/820057/4497974/642633fc-4a74-11e4-9716-bc929875f5c8.png)

It would be nice to publish sources + javadoc, if it wasn't before, or am I missing something obvious here?

**Comment by stanch** [comment]
Seems to work for me — feel free to reopen.
