### ISSUE TITLE
Missing link between Future and UI?

### ISSUE THREAD

**Issue by sgrif** [macroid/macroid#48]
I've been tinkering with type signatures for quite some time, and can't find a way to write this without relying on `runUi` (which if `Ui` is analogous to `IO` in Haskell, we should treat `runUi` as something to be avoided, same as `unsafePerformIO` in Haskell).

The specific use case is this: When the user clicks a button, we submit a form to a server, and depending on the result will either display a toast, or go to the next screen. The signatures are roughly:

```scala
def submitForm: Future[String \/ ResponseData] = {
  // form submission code irrelevant
}

def handleResponse(response: String \/ ResponseData): Ui[Unit] =
  response.map(goToNextScreen).valueOr(displayError)

def goToNextScreen(data: ResponseData): Ui[Unit] = Ui {
  // create intent and pass data as extras, details irrelevant
}

def displayError(message: String): Ui[Unit] =
  toast(message) <~ fry
```

Now ultimately `On.click` needs a `Ui[Any]`, but given any asynchronous action, I have no way to convert from a `Ui[Future[Ui[A]]]` to a `Ui[Future[A]]`. The simplest solution would seem to be adding a method to `Ui` of a type that looks something like:

```scala
def ~~>[B, C](next: C => Ui[B])(implicit ev: A <:< Future[C]): Ui[Future[B]]
```

Which would let me write my code as

```scala
w[Button] <~ On.click(Ui(submitForm) ~~> handleResponse _)
```

For the record, my code is currently

```scala
Ui {
  submitForm().flatMapUi(handleResponse _ >>> runUi[Unit])
}
```

**Comment by sgrif** [comment]
Alternatively, it seems like it would make sense for `mapUi`, `flatMapUi`, etc on Future to return a `Ui[A]` not a `Future[A]`

**Comment by stanch** [comment]
Hi,

First of all your code samples remind me that there are a few places where it makes sense to evaluate arguments lazily :) In parciluar, I keep forgetting to fix it [here](https://github.com/macroid/macroid/blob/master/macroid-core/src/main/scala/macroid/DialogDsl.scala#L47), but `Ui#~` and `Ui#~~` will also benefit from that. I’ll look into it this weekend.

Regarding `mapUi` & co, I’m also not fond of their integration (or rather lack thereof) with `Ui`, but I’m not sure I fully understand the semantics of what you propose. Consider:
```scala
val x: Future[String] = Future { Thread.sleep(5000); "ready in five" }
val y: Ui[Unit] = x mapUi actionBar.setTitle
```
In this case `runUi(y)` will trigger an action that sets the title (on the UI thread) once `x` is ready, right? However we are no longer tracking the effect of things “taking time to execute” — `Ui[Future[A]]` would be a more faithful type, but that’s effectively the same as just doing `Ui(x mapUi ...)`.

What if `flatMapUi` had a signature of `(A ⇒ Ui[B]) ⇒ Future[B]` instead? I remember someone suggesting this before. You code could look like this:
```scala
w[Button] <~ On.click(Ui(submitForm flatMapUi handleResponse))
```
I think that might work, what do you reckon?

**Comment by sgrif** [comment]
> In this case `runUi(y)` will trigger an action that sets the title (on the UI thread) once `x` is ready, right? However we are no longer tracking the effect of things “taking time to execute” — `Ui[Future[A]]`

I would argue that the type `Ui[A]` shouldn't contain semantics about when the action actually occurs, and that whether it's asynchronous should be intentionally ambiguous. This is already the case today, since `Future[A]` is an effector, and the return type of `w[TextField] <~ someFuture.map(text)` is `Ui[TextField]`, even though the action on that text field is being applied asynchronously, and `runUi(resultOfThatExpression)` will set the text (on the UI thread) once `someFuture` is ready.

> What if flatMapUi had a signature of (A ⇒ Ui[B]) ⇒ Future[B] instead? I remember someone suggesting this before. 

Yeah, that sounds reasonable to me as well.

**Comment by stanch** [comment]
> I would argue that the type Ui[A] shouldn't contain semantics about when the action actually occurs, and that whether it's asynchronous should be intentionally ambiguous.

That’s a fair point. My argument was more about the `mapUi: Ui[A]` not being very useful in terms of chaining methods on top of it. With both the current and the updated version you can say “and then do this”.

OK, I’ll try to find time this weekend to update `flatMapUi` & co.

**Comment by stanch** [comment]
Could you try with the new commit? :)

**Comment by sgrif** [comment]
Yes, I'll report back on Monday.

**Comment by sgrif** [comment]
The inner Ui Action is never called.

```scala
w[Button] <~ On.click(loadData)

// ...

def loadData = Ui {
  doHttpRequest.mapUi(goToNextScreen)
}

def doHttpRequest: Future[Data] = ??? // Implementation unimportant, the future is definitely resolving

def goToNextScreen(data: Data): Ui[Unit] = {
  println("This line is called")
  Ui {
    println("This line is never claled")
    val intent = new Intent(this, classOf[NextScreenActivity])
    startActivity(intent)
  }
}

**Comment by sgrif** [comment]
Most of the details left out of that example for brevity. One other thing that shouldn't matter is that I'm submitting data from another view to the server, so ultimately the type of `loadData` is `Ui[Maybe[Future[Unit]]]`

**Comment by sgrif** [comment]
It appears I'm not applying the github dependency properly. Going to try to manually publish locally...

**Comment by sgrif** [comment]
Yes, this change works great for my needs. Any chance of a 2.0.0-M4 release any time soon?

**Comment by stanch** [comment]
Great! Yeah, I can do it in the next few days. There are a couple of other unreleased bugfixes, but I need to recover my publishing settings, because they were not checked in to git and I lost my old filesystem :)

**Comment by stanch** [comment]
FYI I’ve published the artifacts, but still need to update some of the docs and write a changelog, so the official announcement will be a bit later.
