### ISSUE TITLE
Should ID generation be a singleton?

### ISSUE THREAD

**Issue by sgrif** [macroid/macroid#55]
Ran into an issue today where I finally needed to put an ID on something. Specifically it's an image button (no other way to identify it besides ID), which is created inside of a view rather than the activity. Even if I mixed `IdGeneration` into the activity to access it from my tests, I'd potentially get back different IDs since it will use a different cache. Ultimately I now have this in my application:

```
package ui

object Id extends macroid.IdGen(1000)
```

Should the `FullDsl` object just include a singleton instance?

**Comment by stanch** [comment]
It is indeed a problem, but I’m not sure that a singleton is a good solution. It’s mostly just a gut feeling, but I do have one objective argument: it’s harder to configure the starting ID for a singleton, which may or may not be an important thing to do.

**Comment by sgrif** [comment]
In that case, how would you feel about a documentation change that recommends creating an app wide singleton, instead of mixing in the trait?

**Comment by stanch** [comment]
I haven’t come up with any other issues, so that sounds good. In fact, we can remove the `IdGeneration` trait to emphasize this more. But I think it’s a good idea to replace the current locking scheme with a `ConcurrentHashMap`.

**Comment by sgrif** [comment]
I agree with all of those things. I'll submit a PR tonight.

**Comment by stanch** [comment]
See the linked PR. I think `ConcurrentHashMap` wouldn’t really work, because we need to lock the counter globally anyway.
