### ISSUE TITLE
Viewable + Custom ViewablePagerAdatpter

### ISSUE THREAD

**Issue by stilomatic** [macroid/macroid#66]
I am not sure if this is an issue or not:
I need to subclass the ViewablePagerAdatpter to override getPageWidth and have more pages visible together:

```scala
import android.view.View
import macroid.viewable.{Viewable, ViewablePagerAdapter}
import macroid.{ActivityContext, AppContext}

class NavbarCalendarAdapter[A, +W <: View](data: Seq[A])
(implicit ctx: ActivityContext, appCtx: AppContext, viewable: Viewable[A, W])
  extends ViewablePagerAdapter(data: Seq[A]) {

  override def getPageWidth(position: Int): Float = 1/3

}
```

In my Fragment Class i got the onCreate setted in this way:

```scala
override def onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle) = getUi {

    val lps = lp[LinearLayout](MATCH_PARENT, WRAP_CONTENT, Gravity.CENTER_HORIZONTAL) + padding(12,24,12,0)
    val pagerLps = lp[LinearLayout](MATCH_PARENT, 64, Gravity.CENTER_HORIZONTAL) + padding(0,-6,0,0)

    implicit def dateViewable: Viewable[MenuDate, TextView] =
      Viewable[MenuDate] { myDate ⇒ 
w[TextView] <~ 
TextTweaks.size(10 sp) <~ 
text(myDate.value) <~ 
TextTweaks.color(Color.RED) <~
lp[LinearLayout](WRAP_CONTENT, WRAP_CONTENT, Gravity.TOP)
      }

    val pageAdapter = new NavbarCalendarAdapter(dates)

         l[LinearLayout](
          w[ViewPager] <~ wire(this.dateMenu) <~ PagerTweaks.adapter(pageAdapter)
    ) <~ horizontal) <~ Styles.topBar
  }
```

I declared the Viewable implicit cause have to be passed implicitly to the ViewablePagerAdapter subclass.

if i print the Viewable instance inside the ViewablePagerAdapter subclass everything is seated fine.

No error, everything compile and run fine, but the Viewable Pages are never visible.

If instead i use the: dateViewable.pagerAdapter(dates) or the Tweak to create the adapter i can see the Viewable correctly rendered.

**Comment by stanch** [comment]
Hi,

Can it be because of this?
```scala
@ val x: Float = 1 / 3
x: Float = 0.0F
```
Could you try `1f / 3`?

**Comment by stilomatic** [comment]
Thanks Nick 

Yes IT was the float now IT work
I tell You i am a newby with scala.

**Comment by stanch** [comment]
Glad to know!
